# Generated by Django 5.1.1 on 2024-09-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_companhia_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='companhia',
            name='senha',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
